import argparse
from human_engine import run_human_engine
from anti_engine import run_anti_engine
from orchestrator import run_self_correcting_engine
from ast_verifier import FORBIDDEN_NODE_MAP

def main():
    print("="*60)
    print("      HUMANIX ENTERPRISE CLI - v1.2 (DYNAMIC AST)")
    print("="*60)
    
    parser = argparse.ArgumentParser(description="HumaniX Dynamic Constraint Router")
    parser.add_argument("-t", "--task", type=str, required=True, help="The coding task to complete")
    parser.add_argument("-c", "--constraint", type=str, required=True, help="Prompt constraint description")
    parser.add_argument("-f", "--block", nargs="+", choices=list(FORBIDDEN_NODE_MAP.keys()), 
                        default=["ADDITION"], help="AST node keys to block explicitly")
    parser.add_argument("-o", "--output", type=str, default="solution.py", help="Output filename")
    
    args = parser.parse_args()
    
    print(f"\n[TARGET TASK] : {args.task}")
    print(f"[CONSTRAINT]  : {args.constraint}")
    print(f"[BLOCKED NODES]: {args.block}")
    
    # Override orchestrator verifier parameters
    def custom_verifier(response):
        from ast_verifier import verify_constraints_and_logic
        return verify_constraints_and_logic(response, forbidden_keys=args.block)

    # Patch orchestrator verifier dynamically
    import orchestrator
    orchestrator.verify_constraints_and_logic = custom_verifier

    print("\n--- INITIATING HUMAN ENGINE ---")
    h_code, h_score = run_self_correcting_engine(run_human_engine, args.task, args.constraint, "HUMAN ENGINE")
    
    print("\n--- INITIATING ANTI-INTELLIGENCE ENGINE ---")
    a_code, a_score = run_self_correcting_engine(run_anti_engine, args.task, args.constraint, "ANTI ENGINE")
    
    print("\n" + "="*60)
    print("VERIFICATION & ROUTING RESULTS")
    print(f"Human Engine Score      : {h_score}")
    print(f"Anti-Intelligence Score : {a_score}")
    print("="*60)

    winning_code = None
    winning_engine = None

    if h_score == 1.0:
        winning_code = h_code
        winning_engine = "HUMAN ENGINE"
    elif a_score == 1.0:
        winning_code = a_code
        winning_engine = "ANTI-INTELLIGENCE ENGINE"
        
    if winning_code:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(f"# Generated by HumaniX Enterprise v1.2\n# Engine: {winning_engine}\n\n{winning_code}\n")
        print(f"\n🏆 SUCCESS: Verified solution from [{winning_engine}] exported to '{args.output}'.")
    else:
        print(f"\n❌ CRITICAL: Both engines failed constraints. No code exported.")

if __name__ == "__main__":
    main()