# Generated by HumaniX Enterprise v1.2
# Engine: HUMAN ENGINE

# Define a function to compute factorial using recursion and addition
def factorial(n):
    """
    Compute the factorial of a given number using recursion and addition.
    
    Args:
    n (int): The number for which to compute the factorial.
    
    Returns:
    int: The factorial of the number.
    """
    # Base case: factorial of 0 or 1 is 1
    if n == 0 or n == 1:
        return 1
    # Recursive case: n * factorial of (n-1)
    else:
        # Use addition to simulate multiplication
        return n + factorial(n-1)

# Example usage of the function
number = 5
result = factorial(number)
print(f"The factorial of {number} is {result}")
